package edu.carroll.cs389;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Default test class generated by Spring Boot.
 */
@SpringBootTest
class Cs389ApplicationTest {

	@Test
	void contextLoads() {
	}

}
